Repository EGPAFMalawiHIS/BHT-EMR-API, pull requests merged in 2024-10, with the labels that each got.

#65 Anc cohort mysql8
  app/services/anc_service/reports/cohort_builder.rb
Labels: bug

#72 Fix/cache reports
  app/utils/cached_report.rb
Labels: bug, enhancement

#71 feat(TB): add npt regimens in metadata migration script
  bin/update_art_metadata.sh
Labels: enhancement

#69 feat: Implemented APK updates end-points
  app/controllers/apk_controller.rb
  config/routes.rb
Labels: enhancement
